version: "3.9"
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379" # Expose Redis on default port
    command: ["redis-server", "--appendonly", "no"] # No persistence
    networks:
      - redis-network

networks:
  redis-network:
